# Continuous Integration for house-pricing-api
# Runs tests and linter on pull requests

name: CI
permissions:
  contents: read

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          pip install uv


      - name: Install dependencies
        run: |
          uv sync

      - name: Run Ruff linter
        run: |
          uv run ruff check .

      - name: Run Pytest
        run: |
          uv run pytest
